ExamenApp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'ExamenApp'

urlpatterns = [
    path('', views.index, name='index'),
    path('registrar/', views.registrar_usuario, name='registrar_usuario'),
    path('listado_ensayos/', views.listado_ensayos, name='listado_ensayos'),
    path('ensayo/<int:ensayo_id>/', views.detalle_ensayo, name='detalle_ensayo'),
    path('ensayo/crear/', views.crear_ensayo, name='crear_ensayo'),
    path('ensayo/buscar/', views.buscar_ensayo, name='buscar_ensayo'),
    path('ensayo/editar/<int:ensayo_id>/', views.editar_ensayo, name='editar_ensayo'),
    path('ensayo/eliminar/<int:ensayo_id>/', views.eliminar_ensayo, name='eliminar_ensayo'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ExamenApp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]
handler404 = 'ExamenApp.views.mi_error_404'
handler400 = 'ExamenApp.views.mi_error_400'
handler500 = 'ExamenApp.views.mi_error_500'
handler403 = 'ExamenApp.views.mi_error_403'

ExamenApp/models.py
from django.db import models 
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Usuario(AbstractUser):
    ADMINISTRADOR = 1
    INVESTIGADOR = 2
    PACIENTE = 3
    ROLES = (
        (ADMINISTRADOR, 'administrador'),
        (INVESTIGADOR, 'investigador'),
        (PACIENTE, 'paciente'),
    )
    
    rol = models.PositiveSmallIntegerField(
        choices=ROLES, default=1
    )

class Investigador(models.Model):
   usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE, null=True)
   
   def __str__(self):
       return self.usuario.username
   
class Paciente(models.Model):
   usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE, null=True)
   
   def __str__(self):
       return self.usuario.username
   
class Farmaco(models.Model):
   nombre = models.CharField(max_length=100)
   apto_para_ensayos = models.BooleanField()
   
   def __str__(self):
       return self.nombre
   
class EnsayoClinico(models.Model):
   nombre = models.CharField(max_length=100)
   descripcion = models.TextField()
   farmaco = models.ForeignKey(Farmaco, on_delete=models.CASCADE)
   pacientes = models.ManyToManyField('Paciente')
   nivel_seguimiento = models.IntegerField()
   fecha_inicio = models.DateField()
   fecha_fin = models.DateField()
   activo = models.BooleanField(default=True)
   creado_por = models.ForeignKey('Investigador', on_delete=models.CASCADE)  
   
   def __str__(self):
       return self.nombre

ExamenApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Q, Avg, Max, Min, Count, Sum
from django.contrib.auth.hashers import make_password
from datetime import datetime
from .models import *
from .form import *
import ExamenApp.form as form_module 
from django.contrib.auth.views import PasswordChangeView, PasswordResetConfirmView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth import logout

# -------------------------------
# VISTA: Errores
# -------------------------------
def mi_error_404(request, exception=None):
    return render(request, "errores/404.html", status=404)

def mi_error_500(request):
    return render(request, "errores/500.html", status=500)

def mi_error_403(request, exception=None):
    return render(request, "errores/403.html", status=403)

def mi_error_400(request, exception=None):
    return render(request, "errores/400.html", status=400)

# -------------------------------------------------------------------
# Registro de Usuario (Público)
# -------------------------------------------------------------------
def registrar_usuario(request):
    if request.method == 'POST':
        formulario = RegistroForm(request.POST)
        if formulario.is_valid():
            user = formulario.save()
            rol = int(formulario.cleaned_data.get('rol'))
            # Asignar grupo y crear perfil según el rol
            if rol == Usuario.INVESTIGADOR:
                grupo, _ = Group.objects.get_or_create(name='Investigadores')
                user.groups.add(grupo)
                Investigador.objects.create(usuario=user)
            elif rol == Usuario.PACIENTE:
                grupo, _ = Group.objects.get_or_create(name='Pacientes')
                user.groups.add(grupo)
                Paciente.objects.create(usuario=user)
            messages.success(request, "Registrado correctamente.")
            login(request, user)
            return redirect('ExamenApp:index')
    else:
        formulario = RegistroForm()
    return render(request, 'registration/signup.html', {'formulario': formulario})

# -------------------------------
# VISTA: Página de inicio
# -------------------------------
def index(request):
    # VARIABLE SESIÓN 1: Fecha inicio (Global)
    if "fecha_inicio" not in request.session:
        request.session["fecha_inicio"] = datetime.now().strftime("%Y-%m-%d %H:%M")
        
    return render(request, 'examen/index.html')

# -------------------------------------------------------------------
# VISTA: Listado de Ensayos Clínicos 
# -------------------------------------------------------------------
@login_required
def listado_ensayos(request):
    qs=EnsayoClinico.objects.all()
    if request.user.rol == Usuario.PACIENTE:
        paciente = get_object_or_404(Paciente, usuario=request.user)
        qs = qs.filter(pacientes=paciente)
    elif request.user.rol == Usuario.INVESTIGADOR:
        investigador = get_object_or_404(Investigador, usuario=request.user)
        qs = qs.filter(creado_por=investigador)
    return render(request, 'examen/lista_ensayos.html', {'ensayos': qs.all()})

# -------------------------------------------------------------------
# VISTA: Detalle de Ensayo Clínico
# -------------------------------------------------------------------
@login_required
def detalle_ensayo(request, ensayo_id):
    ensayo = get_object_or_404(EnsayoClinico, id=ensayo_id)
    return render(request, 'examen/ensayo_detail.html', {'ensayo': ensayo})

# -------------------------------------------------------------------
# VISTA: Crear Ensayo Clínico
# -------------------------------------------------------------------
@login_required
@permission_required('ExamenApp.add_ensayoclinico')
def crear_ensayo(request):
    if request.method == 'POST':
        formulario = EnsayoClinicoForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Ensayo Clínico creado correctamente.")
            return redirect('ExamenApp:listado_ensayos')
    else:
        formulario = EnsayoClinicoForm()
    return render(request, 'Crud_EnsayoClinico/crear_ensayo.html', {'formulario': formulario})

# -------------------------------------------------------------------
# VISTA: Búsqueda avanzada de Ensayos Clínicos 
# -------------------------------------------------------------------
@login_required
@permission_required('ExamenApp.view_ensayoclinico')
def buscar_ensayo(request):
    formulario = form_module.BusquedaEnsayoForm(request.GET or None)
    resultados = []
    if formulario.is_valid():
        nombre = formulario.cleaned_data.get('nombre')
        qs = EnsayoClinico.objects.filter(nombre__icontains=nombre)
        if request.user.rol == Usuario.PACIENTE:
            paciente = get_object_or_404(Paciente, usuario=request.user)
            qs = qs.filter(pacientes=paciente)
        elif request.user.rol == Usuario.INVESTIGADOR:
            investigador = get_object_or_404(Investigador, usuario=request.user)
            qs = qs.filter(creado_por=investigador)
        resultados = qs
        
        return render(request, 'Crud_EnsayoClinico/ensayo_busqueda.html', {'formulario': formulario, 'resultados': resultados})
    
    return render(request, 'Crud_EnsayoClinico/buscar_ensayo.html', {'formulario': formulario, 'resultados': resultados})

# -------------------------------------------------------------------
# VISTA: Editar Ensayo Clínico
# -------------------------------------------------------------------
@login_required
@permission_required('ExamenApp.change_ensayoclinico')
def editar_ensayo(request, ensayo_id):
    ensayo = get_object_or_404(EnsayoClinico, id=ensayo_id)
    if request.method == 'POST':
        formulario = EnsayoClinicoForm(request.POST, instance=ensayo)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Ensayo Clínico actualizado correctamente.")
            return redirect('ExamenApp:listado_ensayos')
    else:
        formulario = EnsayoClinicoForm(instance=ensayo)
    return render(request, 'Crud_EnsayoClinico/editar_ensayo.html', {'formulario': formulario, 'ensayo': ensayo})

# -------------------------------------------------------------------
# VISTA: Eliminar Ensayo Clínico
# -------------------------------------------------------------------
@login_required
@permission_required('ExamenApp.delete_ensayoclinico')
def eliminar_ensayo(request, ensayo_id):
    ensayo = get_object_or_404(EnsayoClinico, id=ensayo_id)
    ensayo.delete()
    messages.success(request, "Ensayo Clínico eliminado.")
    return redirect('ExamenApp:listado_ensayos')

ExamenApp/templates/examen/base.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}ExamenApp - Preparación{% endblock %}</title>
    {% load static %}
    {% load django_bootstrap5 %}
    {% load bootstrap_icons %}
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'examen/css/styles.css' %}">
</head>
<body>
    <header>
        {% include 'examen/nav.html' %}
    </header>

    <main class="container">
        {% block content %}
            {% endblock %}
    </main>

    <footer>
        {% include 'examen/footer.html' %}
    </footer>

    {% bootstrap_javascript %}
</body>
</html>

ExamenApp/templates/examen/ensayo_detail.html
{% extends 'examen/base.html' %}
{% load static %}

{% block title %}ExamenApp - Detalle del Ensayo Clínico{% endblock %}

{% block content %}
    {% if ensayos %}
    <section class="ensayo-detail">
        <h1>Detalle del Ensayo Clínico: {{ ensayo.nombre }}</h1>
        <ul>
            <li><strong>Descripción:</strong> {{ ensayo.descripcion }}</li>
            <li><strong>Fármaco:</strong> {{ ensayo.farmaco.nombre }}</li>
            <li><strong>Nivel de Seguimiento:</strong> {{ ensayo.nivel_seguimiento }}</li>
            <li><strong>Fecha de Inicio:</strong> {{ ensayo.fecha_inicio }}</li>
            <li><strong>Fecha de Final:</strong> {{ ensayo.fecha_fin }}</li>
            <li><strong>Activo:</strong> {{ ensayo.activo }}</li>
            <li><strong>Creado Por:</strong> {{ ensayo.creado_por }}</li>
            <li><strong>Número de Pacientes Inscritos:</strong> {{ ensayo.pacientes.count }}</li>
            </li>
        </ul>
        <a href="{% url 'ExamenApp:listado_ensayos' %}">Volver al Listado de Ensayos</a>
    </section>
    {% else %}
        <h2>No se encontró el ensayo clínico solicitado.</h2>
        <a href="{% url 'ExamenApp:listado_ensayos' %}">Volver al Listado de Ensayos</a>
    {% endif %}
{% endblock %}

ExamenApp/templates/examen/footer.html
{% load static %}
<div class="footer-content">
    <p>&copy; 2025 ExamenApp. Preparación para el Examen de Django.</p>
</div>

ExamenApp/templates/examen/index.html
{% extends 'examen/base.html' %}
{% load static %}

{% block title %}ExamenApp - Inicio del Test{% endblock %}

{% block content %}
    <section class="hero">
        <h1>¡Bienvenido/a al Examen de Django!</h1>
        <p>
            Fecha de inicio de la sesión: {{ request.session.fecha_inicio }}
        </p>
        </div>
    </section>
{% endblock %}

ExamenApp/templates/examen/lista_ensayos.html
{% extends 'examen/base.html' %}

{% load static %}

{% block title %}ExamenApp - Listado de Ensayos Clínicos{% endblock %}

{% block content %}
    <h1>Listado de Ensayos Clínicos</h1>
    <table border="1">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Farmaco</th>
                <th>Pacientes</th>
                <th>Nivel de Seguimiento</th>
                <th>Fecha de Inicio</th>
                <th>Fecha de Final</th>
                <th>Activo</th>
                <th>Creado Por</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for ensayo in ensayos %}
            <tr>
                <td>{{ ensayo.nombre }}</td>
                <td>{{ ensayo.descripcion }}</td>
                <td>{{ ensayo.farmaco.nombre }}</td>
                <td>{{ ensayo.pacientes.count }}</td>
                <td>{{ ensayo.nivel_seguimiento }}</td>
                <td>{{ ensayo.fecha_inicio }}</td>
                <td>{{ ensayo.fecha_fin }}</td>
                <td>{{ ensayo.activo }}</td>
                <td>{{ ensayo.creado_por }}</td>
                <td>
                    {% if perms.ExamenApp.view_ensayoclinico %}
                    <a class="btn btn-sm btn-outline-primary me-2 text-nowrap" href="{% url 'ExamenApp:detalle_ensayo' ensayo.id %}">Ver en detalle</a>
                    {% endif %}
                    {% if perms.ExamenApp.change_ensayoclinico %}
                    <a class="btn btn-sm btn-outline-secondary me-2 text-nowrap" href="{% url 'ExamenApp:editar_ensayo' ensayo.id %}">Editar</a>
                    {% endif %}
                    {% if perms.ExamenApp.delete_ensayoclinico %}
                    <a class="btn btn-sm btn-outline-danger" href="{% url 'ExamenApp:eliminar_ensayo' ensayo.id %}" onclick="return confirm('¿Estás seguro de que deseas eliminar esta venta?');">Eliminar</a>
                    {% endif %}
                </td>
                
            </tr>
            {% empty %}
            <tr>
                <td colspan="10">No hay ensayos clínicos disponibles.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'ExamenApp:index' %}">Volver al inicio</a>
{% endblock %}

ExamenApp/templates/examen/nav.html
{% load static %}
<style>

    .btn-auth.logout{
        color: white;
    }

</style>

<nav class="navbar">
    <div class="logo">
        <img src="{% static 'examen/images/logo.png' %}" alt="Logo ExamenApp" class="logo-img">
        <span>ExamenApp</span>
    </div>
    
    <ul class="nav-links">
        {% if perms.ExamenApp.add_ensayoclinico %}
        <li><a href="{% url 'ExamenApp:crear_ensayo' %}">Crear Ensayo</a></li>
        {% endif %}
        <li><a href="{% url 'ExamenApp:listado_ensayos' %}">Listar Ensayos</a></li>
        {% if perms.ExamenApp.view_ensayoclinico %}
        <li><a href="{% url 'ExamenApp:buscar_ensayo' %}">Búsqueda avanzada</a></li>
        {% endif %}
    </ul>
    
    <div class="auth-group">
        {% if not user.is_authenticated %}
            <div class="auth-buttons">
                <a href="{% url 'login' %}" class="btn-auth login">Login</a>
                <a href="{% url 'ExamenApp:registrar_usuario' %}" class="btn-auth register">Registrarse</a>
            </div>
        {% else %}
            <div class="auth-buttons">
                <span class="welcome-msg">Bienvenid@, {{ user.username }}</span>
                <form action="{% url 'logout' %}" method="post" class="d-flex w-100">
                        {% csrf_token %}
                        <button type="submit" class="dropdown-item text-danger">
                        <i class="bi bi-box-arrow-right"></i> Cerrar Sesión
                    </button>
                </form>
            </div>
        {% endif %}
    </div>
</nav>